jQuery(document).ready(function($){"use strict";$('a[data-rel]').each(function(){$(this).attr('rel',$(this).data('rel'));});$(".pretty-gallery a[rel^='prettyPhoto']").prettyPhoto();if($('#cp_header').length){var stickyNavTop=$('#cp_header').offset().top;var stickyNav=function(){var scrollTop=$(window).scrollTop();if(scrollTop>stickyNavTop){$('#cp_header').addClass('cp_sticky');}else{$('#cp_header').removeClass('cp_sticky');}};stickyNav();$(window).scroll(function(){stickyNav();});}
if($('.cp_banner').length){var banner_stickyHoldTop=$('.cp_banner').offset().top;var banner_stickyHold=function(){var scrollTop=$(window).scrollTop();if(scrollTop>banner_stickyHoldTop){$('.cp_banner').addClass('cp_banner-sticky');}else{$('.cp_banner').removeClass('cp_banner-sticky');}};banner_stickyHold();$(window).scroll(function(){banner_stickyHold();});}
if($('#cp_banner-slider').length){$("#cp_banner-slider").owlCarousel({navigation:true,slideSpeed:1000,pagination:false,transitionStyle:"fade",autoPlay:true,items:1,itemsDesktop:[1199,1],itemsDesktopSmall:[980,1],itemsTablet:[768,1],itemsMobile:[480,1],});}
if($('#cp_banner-slider2').length){$("#cp_banner-slider2").owlCarousel({navigation:false,slideSpeed:1000,pagination:true,transitionStyle:"fade",autoPlay:true,items:1,itemsDesktop:[1199,1],itemsDesktopSmall:[980,1],itemsTablet:[768,1],itemsMobile:[480,1],});}
if($('#cp_about-slider').length){$("#cp_about-slider").owlCarousel({navigation:true,slideSpeed:500,pagination:false,transitionStyle:"fade",autoPlay:true,navigationText:'',items:1,itemsDesktop:[1199,1],itemsDesktopSmall:[980,1],itemsTablet:[768,1],itemsMobile:[480,1],});}
if($('#cp_about-slider2').length){$("#cp_about-slider2").owlCarousel({navigation:false,slideSpeed:500,pagination:true,transitionStyle:"fade",autoPlay:false,navigationText:'',items:1,itemsDesktop:[1199,1],itemsDesktopSmall:[980,1],itemsTablet:[768,1],itemsMobile:[480,1],});}
if($('#cp_blog-slider').length){$("#cp_blog-slider").owlCarousel({navigation:true,slideSpeed:700,pagination:false,transitionStyle:"fade",autoPlay:false,navigationText:'',items:1,itemsDesktop:[1199,1],itemsDesktopSmall:[980,1],itemsTablet:[768,1],itemsMobile:[480,1],});}
if($('#cp_sidebar-slider').length){$("#cp_sidebar-slider").owlCarousel({navigation:false,slideSpeed:800,pagination:false,transitionStyle:"fade",autoPlay:true,navigationText:'',items:1,itemsDesktop:[1199,1],itemsDesktopSmall:[980,1],itemsTablet:[768,1],itemsMobile:[480,1],});}
if($('#testimonial-slider').length){$('#testimonial-slider').bxSlider({auto:true,mode:'fade',nextText:'',prevText:' ',speed:1000,});}
if($('#product-slider').length){$('#product-slider').bxSlider({auto:true,pagerCustom:'#bx-pager',navigation:false,});}
if($('.portfolioContainer').length){var $container=$('.portfolioContainer');$container.isotope({filter:'*',animationOptions:{duration:750,easing:'linear',queue:false}});$('.cp_portfolioFilter a').on("click",function(){$('.cp_portfolioFilter .current').removeClass('current');$(this).addClass('current');var selector=$(this).attr('data-filter');$container.isotope({filter:selector,animationOptions:{duration:750,easing:'linear',queue:false}});return false;});}
if($('audio').length){$('audio').audioPlayer();}
if($('#map_contact_1').length){var map;var myLatLng=new google.maps.LatLng(48.85661,2.35222);var myOptions={zoom:12,center:myLatLng,zoomControl:true,mapTypeId:google.maps.MapTypeId.ROADMAP,mapTypeControl:false,styles:[{stylers:[{hue:'#cacaca'},{saturation:-100,},{lightness:10}]}],}
map=new google.maps.Map(document.getElementById('map_contact_1'),myOptions);var marker=new google.maps.Marker({position:map.getCenter(),map:map,icon:'Images/map-marker.png',});marker.getPosition();}
if($('#tweecool').length){$('#tweecool').tweecool({username:'crunchpress',limit:3,});}
if($('#event-countdown').length){var austDay=new Date();austDay=new Date(2015,12-1,5,12,15)
$('#event-countdown').countdown({labels:['Years','Months','Weeks','Days','Hours','Minutes','Seconds'],until:austDay});$('#year').text(austDay.getFullYear());}
if($('#event-countdown1').length){var austDay=new Date();austDay=new Date(2015,12-1,5,12,15)
$('#event-countdown1').countdown({labels:['Years','Months','Weeks','Days','Hours','Minutes','Seconds'],until:austDay});$('#year').text(austDay.getFullYear());}
if($('#event-countdown2').length){var austDay=new Date();austDay=new Date(2015,12-1,5,12,15)
$('#event-countdown2').countdown({labels:['Years','Months','Weeks','Days','Hours','Minutes','Seconds'],until:austDay});$('#year').text(austDay.getFullYear());}
if($('#cp_masonrywrap').length){jQuery(function($){function attWookGrid(){var options={itemWidth:261,autoResize:true,container:$('#cp_masonrywrap'),offset:30,flexibleWidth:261};var handler=$('#cp_masonrywrap li');handler.wookmark(options);}
$(window).load(function(){attWookGrid();});});}
$("#cp_back-top").hide();$(function(){$(window).scroll(function(){if($(this).scrollTop()>1000){$('#cp_back-top').fadeIn();}else{$('#cp_back-top').fadeOut();}});$('#cp_back-top a').on("click",function(){$('body,html').animate({scrollTop:0},1000);return false;});});});